name: Archive & Release Draft

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release ${{inputs.tag}}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: create release with assests
      continue-on-error: true
      uses: phuonghuynh/action-ghrelease@v1.1.0
      with:
        repository: phuonghuynh/testci3
        commitish: main
        tag_name: ${{inputs.tag}}
        name: Release ${{inputs.tag}}
        files: 'release ${{inputs.tag}}.zip'
